/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Controles.Controlador;
import Dominio.Analogicas;
import Dominio.Empleado;
import Persistencia.AnalogicasXml;
import Persistencia.EmpleadoXml;
import Persistencia.NumeracionXml;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Moisés
 */
public class AgregarA extends javax.swing.JFrame {

    private Controlador control = new Controlador();
    
    /**
     * Creates new form ListadoE
     */
    //NumeracionXml num = new NumeracionXml();
    AnalogicasXml obj = new AnalogicasXml();
    EmpleadoXml emp = new EmpleadoXml();
    boolean d ;
    public AgregarA() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ƒastHost");
        Preguntar.setVisible(false);
    }
    public AgregarA(NumeracionXml num) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ƒastHost");
        Preguntar.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        min1 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        Preguntar = new javax.swing.JPanel();
        min2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Cedula = new javax.swing.JButton();
        jpIngreso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Digital = new javax.swing.JRadioButton();
        Analogica = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        txtEXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtDesvio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        btnP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 30, 40));

        min1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-deshacer-32.png"))); // NOI18N
        min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min1MouseClicked(evt);
            }
        });
        getContentPane().add(min1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, 40));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, 40));

        Preguntar.setBackground(new java.awt.Color(255, 255, 255));
        Preguntar.setForeground(new java.awt.Color(255, 255, 255));
        Preguntar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        min2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        min2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min2MouseClicked(evt);
            }
        });
        Preguntar.add(min2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 40, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(238, 112, 82));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 255));
        jLabel6.setText("A quien desea asociar esta EXT:");

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(153, 153, 153));
        txtCedula.setText("Ingrese CI");
        txtCedula.setBorder(null);
        txtCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCedulaMouseClicked(evt);
            }
        });
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        Cedula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_OFF.png"))); // NOI18N
        Cedula.setBorder(null);
        Cedula.setBorderPainted(false);
        Cedula.setContentAreaFilled(false);
        Cedula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cedula.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        Cedula.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        Cedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CedulaMouseClicked(evt);
            }
        });
        Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        Preguntar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        getContentPane().add(Preguntar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 360, 270));

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jpIngreso.setPreferredSize(new java.awt.Dimension(290, 612));
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Tipo de Extension:");
        jpIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 160, 20));

        Digital.setBackground(new java.awt.Color(255, 255, 255));
        Digital.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Digital.setForeground(new java.awt.Color(153, 153, 153));
        Digital.setText("Digital");
        Digital.setBorder(null);
        Digital.setContentAreaFilled(false);
        Digital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DigitalMouseClicked(evt);
            }
        });
        Digital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigitalActionPerformed(evt);
            }
        });
        jpIngreso.add(Digital, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        Analogica.setBackground(new java.awt.Color(255, 255, 255));
        Analogica.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Analogica.setForeground(new java.awt.Color(153, 153, 153));
        Analogica.setText("Analogica");
        Analogica.setBorder(null);
        Analogica.setContentAreaFilled(false);
        Analogica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnalogicaMouseClicked(evt);
            }
        });
        Analogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalogicaActionPerformed(evt);
            }
        });
        jpIngreso.add(Analogica, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel15.setBackground(new java.awt.Color(238, 112, 82));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 255));
        jLabel15.setText("Extensión:");
        jpIngreso.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 90, 20));

        txtEXT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEXT.setForeground(new java.awt.Color(153, 153, 153));
        txtEXT.setText("Ingrese Extensión");
        txtEXT.setBorder(null);
        txtEXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEXTMouseClicked(evt);
            }
        });
        txtEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEXTActionPerformed(evt);
            }
        });
        jpIngreso.add(txtEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 180, 40));
        jpIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 40, 40));
        jpIngreso.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 220, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("Nombre:");
        jpIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 70, 20));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Ingrese Nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jpIngreso.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 180, 40));
        jpIngreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 30, 40));
        jpIngreso.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 220, -1));

        jLabel4.setBackground(new java.awt.Color(238, 112, 82));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("Categoria");
        jpIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 20));
        jpIngreso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 40, 40));

        txtCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(153, 153, 153));
        txtCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        txtCategoria.setBorder(null);
        txtCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jpIngreso.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, 30));
        jpIngreso.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 220, -1));

        jLabel9.setBackground(new java.awt.Color(238, 112, 82));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 255));
        jLabel9.setText("Desvio:");
        jpIngreso.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 70, 20));

        txtDesvio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDesvio.setForeground(new java.awt.Color(153, 153, 153));
        txtDesvio.setText("Ingrese Desvio");
        txtDesvio.setBorder(null);
        txtDesvio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDesvioMouseClicked(evt);
            }
        });
        txtDesvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesvioActionPerformed(evt);
            }
        });
        jpIngreso.add(txtDesvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 180, 40));
        jpIngreso.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 40, 40));
        jpIngreso.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 220, -1));
        jpIngreso.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 220, -1));

        jLabel11.setBackground(new java.awt.Color(238, 112, 82));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 255));
        jLabel11.setText("Día:");
        jpIngreso.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 70, 20));
        jpIngreso.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 40, 40));
        jpIngreso.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 140, 40));

        btnP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_OFF.png"))); // NOI18N
        btnP.setBorder(null);
        btnP.setBorderPainted(false);
        btnP.setContentAreaFilled(false);
        btnP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnP.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        btnP.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        btnP.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });
        jpIngreso.add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 120, 40));

        getContentPane().add(jpIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oficina.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1048, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea salir?", "Exit",dialog);
        if (result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void min1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseClicked
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_min1MouseClicked

    private void txtDesvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesvioActionPerformed

    private void txtDesvioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDesvioMouseClicked
        txtDesvio.setText("");
    }//GEN-LAST:event_txtDesvioMouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed

    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        d = Analogica.isSelected();
        if (d  == true) {
            try {
                if(!control.campoEsValido(txtEXT.getText(), "EXT", "Extensión") ||
                   !control.campoEsValido(txtNombre.getName(), "TEXTO", "Nombre") ||
                   !control.campoEsValido(txtDesvio.getText(), "NUMERICO", "Desvío")) {
                    return;
                }
            } catch (Exception ex) {
                Logger.getLogger(AgregarA.class.getName()).log(Level.SEVERE, null, ex);
            }
            Analogicas miAnalogica = new Analogicas(Integer.parseInt(txtEXT.getText()),true,txtNombre.getText(),control.categoria(txtCategoria),Integer.parseInt(txtDesvio.getText()),String.valueOf(txtDate.getDate()));
            obj.agregarAna(miAnalogica);
            txtNombre.setText("");
            txtDesvio.setText("");
            Analogica.setSelected(false);
            Digital.setSelected(false);
            Preguntar.setVisible(true);
        }
        else 
            System.out.println("No es un tipo valido");
       
    }//GEN-LAST:event_btnPActionPerformed

    private void txtEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEXTActionPerformed

    private void txtEXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEXTMouseClicked
        txtEXT.setText("");
    }//GEN-LAST:event_txtEXTMouseClicked

    private void DigitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DigitalMouseClicked
        if (Digital.isSelected()== true){
            Analogica.setSelected(false);
        }
    }//GEN-LAST:event_DigitalMouseClicked

    private void DigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigitalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DigitalActionPerformed

    private void AnalogicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnalogicaMouseClicked
        if (Analogica.isSelected()== true){
            Digital.setSelected(false);

        }
        
    }//GEN-LAST:event_AnalogicaMouseClicked

    private void AnalogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalogicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnalogicaActionPerformed

    private void min2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min2MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_min2MouseClicked

    private void txtCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaMouseClicked
        txtCedula.setText("");
    }//GEN-LAST:event_txtCedulaMouseClicked

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed

    }//GEN-LAST:event_txtCedulaActionPerformed

    private void CedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CedulaMouseClicked
            Empleado est = emp.buscarEmp(Integer.parseInt(txtCedula.getText()));
                if (est == null) {
                    JOptionPane.showMessageDialog(null, "Estudiante no Existe", "Error cédula no encontrada", JOptionPane.ERROR_MESSAGE);
                } else {
                    int ci = Integer.parseInt(txtCedula.getText());
                    int ten = Integer.parseInt(txtEXT.getText());
                    control.modificarDato(emp,ten,ci);
                }
        /*int confirmacion = JOptionPane.showOptionDialog(null, "¿Desea añadir esta Extensión a un empleado?","",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (confirmacion == 0){
            int ci = Integer.parseInt(txtCedula.getText());
            int ten = Integer.parseInt(txtEXT.getText());
            modificarDato(emp,ten,ci);
            
        }else 
            System.out.println("El usuario no EXISTE!!");
        */
    }//GEN-LAST:event_CedulaMouseClicked

    private void CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaActionPerformed
        // TODO add your handling code here:
        try {
            if(!control.campoEsValido(txtCedula.getText(), "CEDULA", "Cédula")) {
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(AgregarA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Analogica;
    private javax.swing.JButton Cedula;
    private javax.swing.JRadioButton Digital;
    private javax.swing.JPanel Preguntar;
    private javax.swing.JButton btnP;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JLabel min;
    private javax.swing.JLabel min1;
    private javax.swing.JLabel min2;
    private javax.swing.JComboBox<String> txtCategoria;
    private javax.swing.JTextField txtCedula;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtDesvio;
    private javax.swing.JTextField txtEXT;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
