/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Controles.Controlador;
import Dominio.Captura;
import Persistencia.CapturaXml;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Moisés
 */
public class AgregarC extends javax.swing.JFrame {

    private Controlador control = new Controlador();
    
    /**
     * Creates new form ListadoE
     */
    CapturaXml obj = new CapturaXml();
    
    public AgregarC() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ƒastHost");
    }
    public AgregarC(CapturaXml emp) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ƒastHost");
    }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        min1 = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        jpIngreso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtLider = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        btnP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_32px.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 30, 40));

        min1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-deshacer-32.png"))); // NOI18N
        min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min1MouseClicked(evt);
            }
        });
        getContentPane().add(min1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, -1, 40));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, 40));

        jpIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jpIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jpIngreso.setPreferredSize(new java.awt.Dimension(290, 612));
        jpIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(51, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 255));
        jLabel2.setText("Crear Grp. Captura:");
        jpIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 160, 20));

        jLabel15.setBackground(new java.awt.Color(238, 112, 82));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 204, 255));
        jLabel15.setText("Nombre:");
        jpIngreso.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 20));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("Ingrese el Nombre");
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jpIngreso.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 180, 40));
        jpIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 40, 40));
        jpIngreso.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 255));
        jLabel3.setText("Lider:");
        jpIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 20));

        txtLider.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLider.setForeground(new java.awt.Color(153, 153, 153));
        txtLider.setText("Ingrese Lider");
        txtLider.setBorder(null);
        txtLider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLiderMouseClicked(evt);
            }
        });
        txtLider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLiderActionPerformed(evt);
            }
        });
        jpIngreso.add(txtLider, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, 40));
        jpIngreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 30, 40));
        jpIngreso.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 220, -1));

        jLabel4.setBackground(new java.awt.Color(238, 112, 82));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 204, 255));
        jLabel4.setText("Captura 1:");
        jpIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, 20));
        jpIngreso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 40, 40));
        jpIngreso.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, -1));

        jLabel9.setBackground(new java.awt.Color(238, 112, 82));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 204, 255));
        jLabel9.setText("Captura 2:");
        jpIngreso.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 20));

        txt2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt2.setForeground(new java.awt.Color(153, 153, 153));
        txt2.setText("0");
        txt2.setBorder(null);
        txt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt2MouseClicked(evt);
            }
        });
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        jpIngreso.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, 40));
        jpIngreso.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 40, 40));
        jpIngreso.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 220, -1));
        jpIngreso.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 220, -1));

        jLabel11.setBackground(new java.awt.Color(238, 112, 82));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 204, 255));
        jLabel11.setText("Captura 3:");
        jpIngreso.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 90, 20));
        jpIngreso.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 40, 40));

        txt3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt3.setForeground(new java.awt.Color(153, 153, 153));
        txt3.setText("0");
        txt3.setBorder(null);
        txt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt3MouseClicked(evt);
            }
        });
        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        jpIngreso.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 180, 40));

        txt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt1.setForeground(new java.awt.Color(153, 153, 153));
        txt1.setText("0");
        txt1.setBorder(null);
        txt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt1MouseClicked(evt);
            }
        });
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        jpIngreso.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, 40));
        jpIngreso.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 220, -1));

        jLabel13.setBackground(new java.awt.Color(238, 112, 82));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 204, 255));
        jLabel13.setText("Captura 4:");
        jpIngreso.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 90, 20));
        jpIngreso.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 40, 40));

        txt4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt4.setForeground(new java.awt.Color(153, 153, 153));
        txt4.setText("0");
        txt4.setBorder(null);
        txt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt4MouseClicked(evt);
            }
        });
        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });
        jpIngreso.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 180, 40));

        btnP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_OFF.png"))); // NOI18N
        btnP.setBorder(null);
        btnP.setBorderPainted(false);
        btnP.setContentAreaFilled(false);
        btnP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnP.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        btnP.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        btnP.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enter_ON.png"))); // NOI18N
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });
        jpIngreso.add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 120, 40));

        getContentPane().add(jpIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/oficina.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1048, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea salir?", "Exit",dialog);
        if (result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void min1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseClicked
        Home h = new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_min1MouseClicked

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt2MouseClicked
        txt2.setText("");
    }//GEN-LAST:event_txt2MouseClicked

    private void txtLiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLiderActionPerformed

    }//GEN-LAST:event_txtLiderActionPerformed

    private void txtLiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLiderMouseClicked
        txtLider.setText("");
    }//GEN-LAST:event_txtLiderMouseClicked

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        try {
            if(!control.campoEsValido(txtNombre.getText(), "TEXTO", "Nombre") ||
               !control.campoEsValido(txtLider.getName(), "TEXTO", "TXT Líder") ||
               !control.campoEsValido(txt1.getText(), "NUMERICO", "Captura 1") ||
               !control.campoEsValido(txt2.getText(), "NUMERICO", "Captura 2") ||
               !control.campoEsValido(txt3.getText(), "NUMERICO", "Captura 3") ||
               !control.campoEsValido(txt4.getText(), "NUMERICO", "Captura 4")) {
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(AgregarA.class.getName()).log(Level.SEVERE, null, ex);
        }
        Captura miCaptura = new Captura(txtNombre.getText(),txtLider.getText(),Integer.parseInt(txt1.getText()),Integer.parseInt(txt2.getText()),Integer.parseInt(txt3.getText()),Integer.parseInt(txt4.getText()));
        obj.agregarCap(miCaptura);
        txtNombre.setText("");
        txt3.setText("");
        txt4.setText("");
        txt1.setText("");
        txtLider.setText("");
        txt2.setText("");
        
    }//GEN-LAST:event_btnPActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt3MouseClicked
        txt3.setText("");
    }//GEN-LAST:event_txt3MouseClicked

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt1MouseClicked
        txt1.setText("");
    }//GEN-LAST:event_txt1MouseClicked

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt4MouseClicked
        txt4.setText("");
    }//GEN-LAST:event_txt4MouseClicked

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnP;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel jpIngreso;
    private javax.swing.JLabel min;
    private javax.swing.JLabel min1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txtLider;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
